name = "TeachingRegistry"
uuid = "e0ac9ab7-178d-4d3a-a0e9-4eb91d077dfa"
repo = "git@github.com:CompGeoInc/teaching_registry.git"
description = "Public registry for learning about the package manager"

[packages]
2f86985e-7aa0-4cfd-87c1-e14ea15ab492 = { name = "Hello", path = "H/Hello" }
